version: "3"
services:
  reverseproxy:
      image: lukastecios/udagram-reverseproxy:latest
      ports:
          - 80:80
      restart: always
      depends_on:
        - api-user
        - api-feed
  api-user:
    image: lukastecios/udagram-api-user:latest
    ports:
      - 8082:8082
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  api-feed:
    image: lukastecios/udagram-api-feed:latest
    ports:
      - 8081:8081
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  frontend:
    image: lukastecios/udagram-frontend:latest
    ports:
      - "8100:80"