version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker images
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker --version
            docker build -t $DOCKERHUB_USERNAME/udagram-reverseproxy udagram-reverseproxy
            docker build -t $DOCKERHUB_USERNAME/udagram-api-user udagram-api-user
            docker build -t $DOCKERHUB_USERNAME/udagram-api-feed udagram-api-feed
            docker build -t $DOCKERHUB_USERNAME/udagram-frontend udagram-frontend
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker tag $DOCKERHUB_USERNAME/udagram-reverseproxy $DOCKERHUB_USERNAME/udagram-reverseproxy:latest
            docker tag $DOCKERHUB_USERNAME/udagram-api-user $DOCKERHUB_USERNAME/udagram-api-user:latest
            docker tag $DOCKERHUB_USERNAME/udagram-api-feed $DOCKERHUB_USERNAME/udagram-api-feed:latest
            docker tag $DOCKERHUB_USERNAME/udagram-frontend $DOCKERHUB_USERNAME/udagram-frontend:latest
            docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:latest
            docker push $DOCKERHUB_USERNAME/udagram-api-user:latest
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:latest
            docker push $DOCKERHUB_USERNAME/udagram-frontend:latest