apiVersion: v1
kind: Service
metadata:
  name: api-feed
  labels:
    app.kubernetes.io/name: api-feed
spec:
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: api-feed