apiVersion: v1
kind: Service
metadata:
  name: api-user
  labels:
    app.kubernetes.io/name: api-user
spec:
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app.kubernetes.io/name: api-user