apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend      
    spec:
      containers:
      - image: lukastecios/udagram-frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80          
      restartPolicy: Always