apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external        
    spec:
      containers:
      - image: lukastecios/udagram-frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80          
      restartPolicy: Always