apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 80
  selector:
    app.kubernetes.io/name: frontend