apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app.kubernetes.io/name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reverseproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reverseproxy
    spec:
      containers:
      - image: lukastecios/udagram-reverseproxy
        name: reverseproxy
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
      restartPolicy: Always