apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app.kubernetes.io/name: reverseproxy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: reverseproxy